"""add bookings ratings routing notifications wishlists

Revision ID: 325affcf48e2
Revises: 9d1e6b3a7f42
Create Date: 2026-08-04 11:13:42.390055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325affcf48e2'
down_revision: Union[str, None] = '9d1e6b3a7f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres enum values can be added in place (no rename/recreate dance
    # needed, unlike the previous role_enum migration which also had to
    # rename existing members) - Alembic's autogenerate doesn't diff enum
    # members at all, so this has to be added by hand.
    op.execute("ALTER TYPE role_enum ADD VALUE IF NOT EXISTS 'TRUST_SAFETY'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_code', sa.String(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'COMPLETED', 'CANCELLED', name='booking_status_enum'), server_default='UPCOMING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_confirmation_code'), 'bookings', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'property_id', name='uq_wishlist_guest_property')
    )
    op.create_index(op.f('ix_wishlists_guest_id'), 'wishlists', ['guest_id'], unique=False)
    op.create_index(op.f('ix_wishlists_property_id'), 'wishlists', ['property_id'], unique=False)
    op.add_column('feedback', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('overall_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('cleanliness_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('communication_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('checkin_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('location_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('value_rating', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('root_cause', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('business_impact', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('executive_summary', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('preventive_recommendation', sa.String(), nullable=True))

    # op.add_column with an Enum type doesn't auto-create the Postgres type
    # the way create_table does - it must be created explicitly first (same
    # fix as the earlier feedback-metadata-columns migration).
    responsible_team_enum = sa.Enum(
        'HOST', 'CUSTOMER_SUPPORT', 'PAYMENTS', 'FINANCE', 'TRUST_AND_SAFETY', 'ENGINEERING', 'PRODUCT',
        name='responsible_team_enum',
    )
    responsible_team_enum.create(op.get_bind(), checkfirst=True)
    guest_decision_enum = sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='guest_decision_enum')
    guest_decision_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('feedback', sa.Column('responsible_team', responsible_team_enum, nullable=True))
    op.add_column('feedback', sa.Column('guest_decision', guest_decision_enum, nullable=True))
    op.add_column('feedback', sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('feedback', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback', sa.Column('sla_breached', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('feedback', sa.Column('duplicate_of_feedback_id', sa.Integer(), nullable=True))
    # Note: autogenerate also flagged 'ix_feedback_embedding_hnsw_cosine' as
    # removed - a false positive (SQLAlchemy's reflection can't see the
    # vector_cosine_ops opclass on the HNSW index), seen on every prior
    # migration in this project. Intentionally omitted; the index is
    # untouched by this migration.
    op.create_index(op.f('ix_feedback_booking_id'), 'feedback', ['booking_id'], unique=False)
    op.create_index(op.f('ix_feedback_duplicate_of_feedback_id'), 'feedback', ['duplicate_of_feedback_id'], unique=False)
    # Named explicitly (not left as None/auto) - an unnamed constraint
    # can't be targeted by drop_constraint() later, which broke downgrade().
    op.create_foreign_key(
        "feedback_booking_id_fkey", "feedback", "bookings", ["booking_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        "feedback_duplicate_of_feedback_id_fkey",
        "feedback", "feedback", ["duplicate_of_feedback_id"], ["id"], ondelete="SET NULL",
    )
    op.add_column('properties', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_properties_host_id'), 'properties', ['host_id'], unique=False)
    op.create_foreign_key(
        "properties_host_id_fkey", "properties", "users", ["host_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_host_id_fkey', 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_host_id'), table_name='properties')
    op.drop_column('properties', 'host_id')
    op.drop_constraint('feedback_duplicate_of_feedback_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_booking_id_fkey', 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_duplicate_of_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_booking_id'), table_name='feedback')
    op.drop_column('feedback', 'duplicate_of_feedback_id')
    op.drop_column('feedback', 'sla_breached')
    op.drop_column('feedback', 'sla_due_at')
    op.drop_column('feedback', 'escalated_at')
    op.drop_column('feedback', 'escalated')
    op.drop_column('feedback', 'guest_decision')
    op.drop_column('feedback', 'responsible_team')
    # Postgres enum types aren't dropped automatically when the column
    # using them is dropped - must be removed explicitly.
    op.execute("DROP TYPE guest_decision_enum")
    op.execute("DROP TYPE responsible_team_enum")
    op.drop_column('feedback', 'preventive_recommendation')
    op.drop_column('feedback', 'executive_summary')
    op.drop_column('feedback', 'business_impact')
    op.drop_column('feedback', 'root_cause')
    op.drop_column('feedback', 'value_rating')
    op.drop_column('feedback', 'location_rating')
    op.drop_column('feedback', 'checkin_rating')
    op.drop_column('feedback', 'communication_rating')
    op.drop_column('feedback', 'cleanliness_rating')
    op.drop_column('feedback', 'overall_rating')
    op.drop_column('feedback', 'booking_id')
    op.drop_index(op.f('ix_wishlists_property_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_guest_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_confirmation_code'), table_name='bookings')
    op.drop_table('bookings')
    # Unlike main_category_enum/etc. in the very first migration (never
    # actually round-trip tested), this WAS tested with a real
    # upgrade->downgrade->upgrade cycle - leaving this type behind made the
    # second upgrade fail with "type already exists", since create_table's
    # inline enum creation isn't checkfirst=True. Fixed here rather than
    # carried forward as a latent bug.
    op.execute("DROP TYPE booking_status_enum")
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    # Postgres has no ALTER TYPE ... DROP VALUE - removing an enum member
    # requires the same rename/recreate/cast dance as the previous role_enum
    # migration. Any TRUST_SAFETY user falls back to SUPPORT_MANAGER, the
    # nearest existing staff role.
    op.execute("ALTER TYPE role_enum RENAME TO role_enum_new")
    role_enum = sa.Enum(
        'GUEST', 'HOST', 'SUPPORT_MANAGER', 'OPS_MANAGER', 'PRODUCT_MANAGER', 'EXEC', name='role_enum'
    )
    role_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute(
        "ALTER TABLE users ALTER COLUMN role TYPE role_enum USING ("
        "CASE role::text WHEN 'TRUST_SAFETY' THEN 'SUPPORT_MANAGER' ELSE role::text END"
        ")::role_enum"
    )
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'GUEST'")
    op.execute("DROP TYPE role_enum_new")
