"""create feedback and themes tables

Revision ID: 68ab49907f0a
Revises: 
Create Date: 2026-07-21 12:01:38.151819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ab49907f0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('main_category', sa.Enum('INCIDENT', 'SERVICE_REQUEST', 'GENERAL_FEEDBACK', name='main_category_enum'), nullable=True),
    sa.Column('sub_category', sa.Enum('PRODUCT_BUG', 'APPLICATION_CRASH', 'LOGIN_ISSUE', 'PAYMENT_FAILURE', 'PERFORMANCE_ISSUE', 'SECURITY_ISSUE', 'DATA_LOSS', 'INTEGRATION_FAILURE', 'FEATURE_REQUEST', 'UI_UX_IMPROVEMENT', 'DOCUMENTATION_REQUEST', 'API_ENHANCEMENT', 'ACCESSIBILITY_IMPROVEMENT', 'NEW_INTEGRATION', 'APPRECIATION', 'COMPLAINT', 'PRICING_FEEDBACK', 'CUSTOMER_SUPPORT', 'QUESTION', 'SUGGESTION', name='sub_category_enum'), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_enum'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_enum'), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('feedback_themes',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_themes')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_table('themes')
    op.drop_table('feedback')
    # ### end Alembic commands ###
