"""add feedback metadata columns

Revision ID: dcca72ebde4d
Revises: 21be712d245b
Create Date: 2026-07-27 11:52:57.167190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcca72ebde4d'
down_revision: Union[str, None] = '21be712d245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column with an Enum type doesn't auto-create the Postgres type
    # the way create_table does - it must be created explicitly first.
    feedback_source_enum = sa.Enum(
        'WEB_FORM', 'IN_APP_WIDGET', 'MOBILE_APP', 'EMAIL', 'API', 'SURVEY', 'CHATBOT', 'QR_CODE',
        name='feedback_source_enum',
    )
    feedback_source_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('feedback', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('name', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('email', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('source', feedback_source_enum, nullable=True))
    op.add_column('feedback', sa.Column('product', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('module', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('version', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('device', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('region', sa.String(), nullable=True))
    # Note: autogenerate also flagged 'ix_feedback_embedding_hnsw_cosine' as
    # removed - a false positive, since SQLAlchemy's reflection can't see
    # the vector_cosine_ops opclass on the HNSW index. That line is
    # intentionally omitted here; the index is untouched by this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'region')
    op.drop_column('feedback', 'platform')
    op.drop_column('feedback', 'browser')
    op.drop_column('feedback', 'device')
    op.drop_column('feedback', 'version')
    op.drop_column('feedback', 'module')
    op.drop_column('feedback', 'product')
    op.drop_column('feedback', 'source')
    op.drop_column('feedback', 'email')
    op.drop_column('feedback', 'name')
    op.drop_column('feedback', 'user_id')
    # Postgres enum types aren't dropped automatically when the column
    # using them is dropped - must be removed explicitly.
    op.execute("DROP TYPE feedback_source_enum")
    # ### end Alembic commands ###
